
<form action="/enrol.php" 
	method="post"      
	enctype="multipart/form-data" >


  <input type="text" placeholder="Enter your email address" autofocus="true" name="Email" />
  <button type=“submit” id=“submit” onclick=“alert(’Thanks’)”>Submit</button>
</form>


<script>
   var i = document.createElement("input");
   i.setAttribute("type", "date");
   if (i.type == "text")
   {
      // No native date picker support
   }
</script>


</body>
</html>
