<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Movies On The Train Blog</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada" rel="stylesheet">
  <link rel="stylesheet" href="/MovieBlog_GIIT/blog_css.css">

</head>
<body> 
    <header>
        <div class="container">
           
            <h1 class="blog-name">Movies On The Train Blog</h1>
        </div>
        <div class="container nav-links">
            <nav class="nav-background">
                <ul>
                <li><a href="/MovieBlog_GIIT/about.php">About</a></li>
                <li><a href="/MovieBlog_GIIT/search.php?search">Search</a></li>
                <li><a href="/MovieBlog_GIIT/login.php">Login</a></li>
                </ul>
           
                </nav>
        </div>
        </header>
  
    
    