<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Movies On The Train Blog</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada" rel="stylesheet">
  <link rel="stylesheet" href="/MovieBlog_GIIT/blog_css.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body> 
    <header>
        <div class="container container-fluid">
           <div class="navbar-header">
                 <a class="navbar-brand blog-name">Movies On The Train Blog</a>
           </div>
             
                    <ul class="nav navbar-nav">
                        <li class="nav-links"><a href="index.php">Home</a></li>
                        <li class="nav-links"><a href="/MovieBlog_GIIT/about.php">About</a></li>
                        <li class="nav-links"><a href="/MovieBlog_GIIT/search.php?search">Search</a></li>
                    </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-links"><a href="/MovieBlog_GIIT/login.php"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
        </div>
             
    </header>
  
    
    